/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        Aldeao meu = new Aldeao();
        Arqueiro dois = new Arqueiro();
        Cavaleiro um = new Cavaleiro();

        System.out.println(meu.atacar());
        System.out.println(meu.mover());

        System.out.println(dois.atacar());
        System.out.println(dois.mover());

        System.out.println(um.atacar());
        System.out.println(um.mover());
    }
}
